---
- name: Play to test connectivity
  hosts: workstation
  environment:
    OS_CLIENT_CONFIG_FILE: ./clouds.yaml

  tasks:
    - debug:

        msg: |
          "{{ lookup('env','OS_CLIENT_CONFIG_FILE')}}"

    - name: Create openstack directory
      become: true
      file:
        path: /etc/openstack
        state: directory

    - name: Copy clouds.yaml
      become: true
      copy:
        src: clouds.yaml
        dest: /etc/openstack

#    OS_USERNAME: "{{ osp_auth_username }}"
#    OS_PASSWORD: "{{ osp_auth_password }}"
#    OS_PROJECT_NAME: "admin"
#    OS_PROJECT_DOMAIN_ID: "{{ osp_auth_project_domain }}"
#    OS_USER_DOMAIN_NAME: "{{ osp_auth_user_domain }}""

    - name: Check connectivity
      os_auth:
      register: os_auth_output

    - debug: var=os_auth_output
